# On merge to master, build a container and deploy to ECR
name: Publish to QA environment

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  publish_qa:
    name: Publish image to ECR
    # only run if PR is merged (not just closed)
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.NYPL_DEV_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.NYPL_DEV_AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          REGISTRY_API_DOMAIN: https://qa-libraryregistry.librarysimplified.org/admin
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: nyplsimplye-registry
          IMAGE_TAG: ${{ github.sha }}

        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          --build-arg REGISTRY_API_DOMAIN=$REGISTRY_API_DOMAIN .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:registry-admin-qa-latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:registry-admin-qa-latest

      - name: Force ECS Update
        run: |
          aws ecs update-service --cluster simplye-registry-admin-qa --service simplye-registry-admin-qa --force-new-deployment
